# Generated by Django 4.1.7 on 2023-03-15 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introduce', '0004_alter_people_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='ability',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='cellphone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='hobby',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
