# Generated by Django 4.1.7 on 2023-03-15 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introduce', '0005_people_ability_people_address_people_cellphone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='ability',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='hobby',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
