# Generated by Django 4.1.7 on 2023-03-15 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introduce', '0006_alter_people_ability_alter_people_hobby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='ability',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='hobby',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
    ]
