# Generated by Django 4.1.7 on 2023-03-15 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introduce', '0009_alter_people_cellphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='job',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
