# Generated by Django 4.1.7 on 2023-03-15 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('introduce', '0010_people_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='ability',
        ),
    ]
